version: "3.7"
services:
  go_chat:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    tty: true
    volumes:
      - .:/go/src/app
    depends_on:
      - "db"
    ports:
      - "8080:8080"
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./db/Dockerfile
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=chat
      - POSTGRES_DB=chat
    hostname: postgres
    expose:
      - 5432

# db mount
